# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        logoheader:
            quality: 75
            filters:
                scale:
                    dim: [ 100 , 100 ]
        miniava:
            quality: 75
            filters:
                scale:
                    dim: [ 90 , 90 ]
        profileava:
            quality: 75
            filters:
                scale:
                    dim: [ 200 , 200 ]