#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Index redirection
index:
  methods: GET
  path: /
  controller: App\Controller\UsersController::index


#calendar
calendar:
  methods: GET
  path: /calendar/{id}
  locale: fr
  controller: App\Controller\EventController::calendar

calendar_get_potential_guests:
  methods: POST
  path: /calendar/seek/{id}
  controller: App\Controller\UsersController::seekInvites

calendar_beg_potential_invites:
  methods: POST
  path: /calendar/beg/{id}
  controller: App\Controller\UsersController::begInvites


#contacts
contacts_index:
  methods: GET
  path: /contacts
  controller: App\Controller\ContactsController::index

contact_create:
  methods: POST
  path: /contact/create
  controller: App\Controller\ContactsController::create

contact_delete:
  methods: DELETE
  path: /contact/delete/{id}
  controller: App\Controller\ContactsController::delete

contact_specific_list:
  methods: POST
  path: /contact/list
  controller: App\Controller\ContactsController::specifList

contact_update:
  methods: PUT
  path: /contact/update/{id}
  controller: App\Controller\ContactsController::update

#cookie setter
cookie_setter:
  methods: POST
  path: /cookie-monster
  controller: App\Controller\UsersController::setShittyCookie

#event CRUD
event_create:
  methods: POST
  path: /event/create/{id}
  controller: App\Controller\EventController::create

event_delete:
  methods: DELETE
  path: /event/{id}
  controller: App\Controller\EventController::delete

event_index:
  methods: GET
  path: /event
  controller: App\Controller\EventController::index

event_get:
 methods: POST
 path: /event/{id}
 controller: App\Controller\EventController::get

event_get_potential_users:
  methods: POST
  path: /event/{id}/getlist
  controller: App\Controller\EventController::forEventInvite

event_update:
  methods: PUT
  path: /event/{id}
  controller: App\Controller\EventController::update


#mails
mail_calendar_invites:
  methods: POST
  path: /mail/calendar/{id}/invite
  controller: App\Controller\TestMailController::dashCalendarInvites

mail_calendar_begging:
  methods: POST
  path: /mail/calendar/{id}/beg
  controller: App\Controller\TestMailController::dashCalendarBeggar

mail_calendar_request:
  methods: POST
  path: /mail/calendar_request
  controller: App\Controller\TestMailController::profileCalendarRequests

mail_event_invite:
  methods: POST
  path: /mail/event/{id}/invite
  controller: App\Controller\TestMailController::eventInvite


#register
register_success:
  methods: GET
  path: /register/success
  controller: App\Controller\RegistrationController::success


#Users route
users_home:
  methods: GET
  path: /home/
  controller: App\Controller\UsersController::home

users_profile:
  methods: GET
  path: /profile/{id}
  controller: App\Controller\UsersController::profile

users_update:
  methods: PUT
  path: /profile/{id}
  controller: App\Controller\UsersController::update

users_updateava:
  methods: POST
  path: /profile/{id}
  controller: App\Controller\UsersController::updateAva
