#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#calendar
calendar:
  methods: GET
  path: /calendar
  locale: fr
  controller: App\Controller\EventController::calendar

#contacts
contact_index:
  methods: GET
  path: /contact
  controller: App\Controller\ContactsController::index

contact_edit:
  methods: GET
  path: /contact/edit/{id}
  controller: App\Controller\ContactsController::edit

contact_new:
  methods: GET
  path: /contact/new
  controller: App\Controller\ContactsController::new

contact_create:
  methods: POST
  path: /contact/create
  controller: App\Controller\ContactsController::create

contact_update:
  methods: PUT
  path: /contact/update/{id}
  controller: App\Controller\ContactsController::update

#event CRUD
event_delete:
  methods: DELETE
  path: /event/{id}
  controller: App\Controller\EventController::delete

event_edit:
  methods: GET|POST
  path: /event/{id}/edit
  controller: App\Controller\EventController::edit

event_index:
  methods: GET
  path: /event
  controller: App\Controller\EventController::index

event_new:
  methods: GET|POST
  path: /event/new
  controller: App\Controller\EventController::new

event_show:
 methods: GET
 path: /event/{id}
 controller: App\Controller\EventController::show

#login
login_index:
  methods: GET
  path: /login
  controller: App\Controller\LoginController::index

#register
register_index:
  methods: GET
  path: /register
  controller: App\Controller\RegisterController::index

register_create:
  methods: POST
  path: /register/create
  controller: App\Controller\RegisterController::create
